### ISSUE TITLE
Pre authentication using OpenID Connect proxy

### ISSUE THREAD

**Issue by devinsaini** [eclipse-ditto/ditto#1569]
I'm trying to setup Ditto with Keycloak authentication in a Kubernetes environment. I see in the documentation that we can either use a pre-authentication mode or OIDC to authenticate. Is my understanding correct that we can also pre-authenticate with an OIDC provider using a proxy like oauth2-proxy?

I currently have the following setup in Rancher RKE2.

```mermaid
graph LR;
    A[Client]-->B[Nginx Ingress];
    B-->C[Ditto Gateway];
    B<-->D[oauth2-proxy];
    D-->E[Keycloak];
```

The authentication flow works fine when I substitute Ditto Gateway with a test service. It asks me for login if not authenticated already, and then returns a response from the service. However, when trying to access a Ditto endpoint, it always returns 401. In gateway logs, I see
```
No applicable authentication provider was found!
```

I have `ENABLE_PRE_AUTHENTICATION` set to true. Am I correct in assuming that I don't need to add Keycloak details in 
`-Dditto.gateway.authentication.oauth.openid-connect-issuers.myprovider.issuer` if I'm using this setup?

One thing pending is I haven't set the header `x-ditto-pre-authenticated`. I'm not sure how to create `<issuer>:<subject>` combination in Nginx Ingress annotations. I do have `x-auth-request-user` header getting forwarded from the Ingress though.
Following is the Ingress definition:
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: X-Auth-Request-User, X-Auth-Request-Email
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: ditto-gateway
  namespace: edgecloud
spec:
  rules:
  - host: example.com
    http:
      paths:
      - backend:
          service:
            name: dragonfly-ditto-gateway
            port:
              number: 8080
        path: /ditto(/|$)(.*)
        pathType: Prefix
```

Another question I have is if I use pre-authentication mode, then can I still use WebSockets with Ditto Gateway.
Thirdly, will I be able to use JWT placeholders to extract scopes, provided I forward the JWT header from oauth2 proxy to nginx and then to Ditto?
